export const checkoutContent = {
  headline: "Votre protocole SRP™",
  subline: "Complétez votre commande en toute sécurité.",
  orderSummaryLabel: "Récapitulatif de votre commande",
  ctaLabel: "Confirmer ma commande",
  securityNote: "Paiement 100 % sécurisé — vos données ne sont jamais stockées.",
  trustBadges: [
    "Paiement sécurisé",
    "Livraison premium",
    "Accès au e-book SRP™",
    "Accès MYMADERO SCULPT™",
    "Possibilité d'accompagnement expert METCARE®",
  ],
  productName: "SIGNATURE RECOVERY PROTOCOL™",
  productMeta: "Protocole complet · METCARE®",
  pricePlaceholder: "—",
  deliveryLabel: "Livraison premium",
  deliveryMeta: "Suivi & assistance",
  totalLabel: "Total",
  expressPaymentLabel: "Paiement express",
  orCardLabel: "ou par carte",
  emailLabel: "Adresse e-mail",
  firstNameLabel: "Prénom",
  lastNameLabel: "Nom",
  cardLabel: "Numéro de carte",
  expiryLabel: "Expiration",
  cvcLabel: "CVC",
  deliverySectionLabel: "Livraison",
  addressLabel: "Adresse",
  zipLabel: "Code postal",
  cityLabel: "Ville",
  countryLabel: "Pays",
  paymentNotConfigured:
    "Le paiement n'est pas encore configuré. Merci de réessayer ultérieurement.",
  genericError: "Une erreur est survenue. Veuillez réessayer.",
  guaranteesAriaLabel: "Garanties",
  priceConfirmPlaceholder: "Prix à confirmer avant mise en ligne.",
} as const;
