export const protocoleContent = {
  contents: {
    sectionNum: "§ 01",
    title: "Ce que contient le protocole",
    products: [
      "DRAIN BOOSTER™",
      "ACTIVE DRAIN™",
      "DAY COLLAGEN™",
      "NIGHT COLLAGEN™",
      "DRAINAGE ACTIVATION GEL™",
      "TISSUE REPAIR CREAM™",
      "SKIN RECOVERY PATCH™",
      "E-BOOK SRP™",
      "MY MADERO SCULPT™",
      "Accompagnement expert METCARE®",
    ],
  },
  experience: {
    sectionNum: "§ 02",
    title: "The SRP™ Experience",
    subtitle: "Un protocole de récupération pensé sur 24 heures.",
    lines: [
      "Plus qu'une box.",
      "Un véritable prolongement de l'expérience METCARE®.",
      "",
      "La SRP™ EXPERIENCE fait partie intégrante du parcours de récupération.",
      "Pensée dans une logique premium, élégante et réutilisable,",
      "elle a été conçue pour prolonger l'expérience bien au-delà du protocole lui-même.",
      "",
      "Les éléments intérieurs peuvent être retirés et réorganisés",
      "afin que la box puisse être conservée et réutilisée :",
      "rangement des produits SRP™,",
      "bijoux,",
      "accessoires,",
      "espace beauté,",
      "ou objet souvenir du parcours METCARE®.",
      "",
      "Parce que chez METCARE®, chaque détail de l'expérience compte.",
    ],
  },
  individual: {
    sectionNum: "§ 03",
    title: "Produits disponibles à l'unité",
    lines: [
      "Le protocole SRP™ peut être suivi dans sa globalité ou personnalisé selon les besoins.",
      "Tous les produits sont également disponibles individuellement.",
    ],
  },
  expert: {
    sectionNum: "§ 04",
    title: "Accompagnement Expert",
    lines: [
      "Le protocole peut également être accompagné par un expert du réseau METCARE®",
      "formé à l'approche SIGNATURE RECOVERY PROTOCOL™",
      "afin d'offrir une expérience encore plus personnalisée et cohérente.",
      "Parce que vous ne devriez jamais vivre votre récupération seule.",
    ],
    ctaLabel: "Découvrir le protocole SRP™",
  },
} as const;
