export const checkoutContent = {
  headline: "Your SRP™ protocol",
  subline: "Complete your order securely.",
  orderSummaryLabel: "Order summary",
  ctaLabel: "Confirm my order",
  securityNote: "100% secure payment — your data is never stored.",
  trustBadges: [
    "Secure payment",
    "Premium delivery",
    "Access to the SRP™ e-book",
    "Access to MYMADERO SCULPT™",
    "METCARE® expert guidance available",
  ],
  productName: "SIGNATURE RECOVERY PROTOCOL™",
  productMeta: "Complete protocol · METCARE®",
  pricePlaceholder: "—",
  deliveryLabel: "Premium delivery",
  deliveryMeta: "Tracking & assistance",
  totalLabel: "Total",
  expressPaymentLabel: "Express payment",
  orCardLabel: "or by card",
  emailLabel: "Email address",
  firstNameLabel: "First name",
  lastNameLabel: "Last name",
  cardLabel: "Card number",
  expiryLabel: "Expiry",
  cvcLabel: "CVC",
  deliverySectionLabel: "Delivery",
  addressLabel: "Address",
  zipLabel: "Postcode",
  cityLabel: "City",
  countryLabel: "Country",
  paymentNotConfigured:
    "Payment is not yet configured. Please try again later.",
  genericError: "An error occurred. Please try again.",
  guaranteesAriaLabel: "Guarantees",
  priceConfirmPlaceholder: "Price to be confirmed before go-live.",
} as const;
